### ISSUE TITLE
Define a list of entry and exit points for PHP

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/attack-surface-metrics#23]
For entry points, let's start with the documentation here: http://php.net/manual/en/reserved.variables.php

Notice how some entire variables are untrusted (e.g. `$_GET` and `$_POST`), but others have untrusted entries in them, e.g. `$_SERVER`. Write the list on this issue of the variables we believe are part of the entry points.

Exit points are going to be harder for web apps, but let's try to make some headway on that.

**Comment by megakevin** [comment]
Not longer being worked on for the time being. Closing.
