### ISSUE TITLE
Explore the research questions manually

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/attack-surface-metrics#26]
Here are some research questions that we should put into the capstone:

* How does the concept of the attack surface apply to PHP applications?
* Do entry and exit points in Wordpress reside within the call graph, or outside the call graph?
* Do vulnerabilities in Wordpress reside within the call graph, or outside the call graph?
* For vulnerabilities that reside within the call graph, how close are they to the entry and exit points.

This does mean that we need some more progress on #23. 

Here's a stretch goal:

* Does the number of entry and exit points increase over time in Wordpress? 

Some literature shows that Microsoft products have decreased their attack surfaces over time, leading the authors to conclude that the system is more secure. I'm wondering if this has applied to Wordpress too. 

The stretch goal will require you to (a) automate the collection of entry and exit points, and (b) check out various versions of Wordpress in SVN and compare the counts.

**Comment by megakevin** [comment]
No longer being worked on for the time being. Closing.
