### ISSUE TITLE
attacksurfacemeter being incorrectly installed

### ISSUE THREAD

**Issue by nuthanmunaiah** [andymeneely/attack-surface-metrics#40]
`pip install attacksurfacemeter` is resulting in the creation of three separate packages:

* `attacksurfacemeter`
* `loaders`
* `formatters`

We may have to modify the directory structure of the repository so that `attacksurfacemeter` is the only package installed, with `loaders` and `formatter` being sub-packages within it.

**Comment by nuthanmunaiah** [comment]
@megakevin: Do you agree that we should modify `formatters` and `loaders` to be submodules of `attacksurfacemeter`?

**Comment by megakevin** [comment]
Sure. I don't see any problem with that.

**Comment by nuthanmunaiah** [comment]
Issue is now resolved. However, there were a few (packaging) bugs that made it through to PyPI .The tainted versions had to be manually removed from PyPI using their web interface. Since PyPI does not allow updating existing versions of the package, I was forced to bump up the version number every time I had to validate a fix. We are at 0.4.0 as of this writing.
